[[redirects]]
  from = "/npm/*"
  to = "https://cdn.jsdelivr.net/npm/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/@supabase/*"
  to = "https://esm.sh/@supabase/:splat"
  status = 200
  force = true
